# Create 1D, 2D arrays with array() and arange().

## Using numpy array

In [2]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [6]:
arr2=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9] 
])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

<class 'numpy.ndarray'>
2
(3, 3)


## using numpy arange()

In [12]:
arr3=np.arange(1,11)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
arr3.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Generate arrays of zeros/ones.

In [17]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(np.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Check array shape, size, and dtype.

In [23]:
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64


## Create a NumPy array of numbers 1–10.

In [25]:
ar5=np.arange(1,11)
print(ar5)

[ 1  2  3  4  5  6  7  8  9 10]


## Generate an array of even numbers between 20 and 40.

In [26]:
ar6 = np.arange(20,41,2)
print(ar6)

[20 22 24 26 28 30 32 34 36 38 40]


## Create an array of 20 random integers (1–50) and extract only the odd numbers.

In [27]:
ar7 = np.random.randint(20,51,20)
od = ar7[ar7%2 != 0]
print(od)

[29 45 49 47 41 29 41 27]


## Compare memory usage of a Python list vs a NumPy array with 1000 element

In [28]:
import sys


py_list = list(range(1000))
print("List size:", sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list))


np_array = np.arange(1000, dtype=np.int32)
print("NumPy array size:", np_array.nbytes)


List size: 36056
NumPy array size: 4000


## Reshape a NumPy array of numbers 1–36 into a 6×6 matrix.

In [4]:
ar8 = np.arange(1,37)
print(ar8)
ar9 = ar8.reshape(6,6)
print(ar9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
