# Reshape, flatten, transpose. Functions: reshape(), ravel(), transpose().

In [1]:
import numpy as np

#### reshape()

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
print(arr)
 

[[1 2 3]
 [4 5 6]]
2


#### flatten()

In [7]:
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6]


#### ravel()

In [11]:
arr1 = np.arange(1,11)
print(arr1)
print()
arr1 = arr1.reshape(2,5)
print(arr1)

arr1 = arr1.ravel()
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


#### transpose()

In [14]:
arr2 = np.arange(1,11).reshape(2,5)
print(arr2)
print(arr2.transpose())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [16]:
arr3 = np.arange(1,25).reshape(2,3,4)
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [19]:
t1 = arr3.transpose()
print(t1)
print(t1.shape)

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
(4, 3, 2)


In [20]:
t2 = arr3.transpose(0,2,1)
print(t2)
print(t2.shape)

[[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]

 [[13 17 21]
  [14 18 22]
  [15 19 23]
  [16 20 24]]]
(2, 4, 3)


#### Convert a 1D array into 2D (3×4).

In [24]:
a1 = np.arange(1,13)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = a1.reshape(3,4) 
print(a2)
print(a2.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### Flatten a matrix into 1D.

In [28]:
a3 = a2.flatten()
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### Transpose a 2D array.

In [29]:
a4 = a2.transpose()
print(a4)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### Create an array of numbers 1–12 and reshape it into a 3×4 matrix

In [30]:
a5 = np.arange(1,13)
print(a5.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Transpose a 2×3 matrix into a 3×2 matrix.

In [32]:
a6 = np.arange(1,7).reshape(2,3)
print(a6)
print(a6.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


#### Reshape numbers 0–29 into a 6×5 matrix and extract the 3rd column.

In [33]:
a7 = np.arange(30)
print(a7)
a8 = a7.reshape(6,5)
print()
print(a8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [35]:
print(a8[:, 2])

[ 2  7 12 17 22 27]


#### Flatten a 3×3 matrix and sort elements in descending order.

In [53]:
a9 = np.random.randint(1,50,(3,3))
print(a9)
a10 = a9.flatten()
print(a10)
print(np.sort(a10[::-1]))


[[23 26 39]
 [23 35 25]
 [10 37 31]]
[23 26 39 23 35 25 10 37 31]
[10 23 23 25 26 31 35 37 39]


#### Create an 8×8 checkerboard pattern using only zeros() and slicing.


In [60]:
a11 = np.zeros((8,8))
print(a11)
print()
a11[:, 1::2] = 1
print(a11)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
