# Stacking, splitting, copying arrays. Functions: hstack(), vstack(), split(), copy().

### stacking

In [1]:
import numpy as np

In [4]:
a = np.arange(1,7).reshape(3,2)
b = np.arange(7,13).reshape(3,2)
print(a)
print()
print(b) 

[[1 2]
 [3 4]
 [5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [41]:
print(np.stack((a,b)))


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
print(np.vstack((a,b)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
print(np.hstack((a,b)))

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
(3, 4)


In [43]:
stack1 = np.stack((a,b), axis=1)
print(stack1)
print(stack1.shape)

[[[ 1  2]
  [ 7  8]]

 [[ 3  4]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]
(3, 2, 2)


#### split()

In [18]:
a1 = np.arange(1,7)
print(a1)

[1 2 3 4 5 6]


In [27]:
split_a1 = np.split(a1, 3)
print(split_a1)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [25]:
a1 = a1.reshape(3,2)
split_a1 = np.array_split(a1, 2)
print(split_a1)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


#### view()

In [30]:
np1 = np.arange(1,10)
np2 = np1.view()
print(np1)
print(np2)
np1[0]=99
print(np2)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[99  2  3  4  5  6  7  8  9]


#### view()

In [31]:
np1 = np.array([1,2,3,4,5,6])
np2 = np1.copy()
print(np1)
print(np2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [32]:
np1[0] = 44
print(np2)

[1 2 3 4 5 6]


### Stack two arrays vertically and horizontally.

In [33]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
vertical = np.vstack((a1,a2))
horiz = np.hstack((a1,a2))
print(vertical)
print(horiz)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Split a 1D array into equal parts.

In [34]:
d1 = np.array([1,2,3,4,5,6,7,8])
split_d1 = np.split(d1, 2)
print(split_d1)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


### Shallow Copy vs Deep Copy

- **Shallow Copy**: Creates a new object, but references (points to) the original elements.  
  → Changes inside nested objects will reflect in both copies.  

- **Deep Copy**: Creates a completely independent copy of the object and all nested objects.  
  → Changes in one will NOT affect the other.


In [53]:
d2 = np.arange(1,11)
print(d2)
d3 = d2.view()  #shallow copy
d3[2] = 100
print(d3)
print(d2)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2 100   4   5   6   7   8   9  10]
[  1   2 100   4   5   6   7   8   9  10]


In [55]:
d2 = np.arange(1,11).reshape((5,2))
d3 = d2.copy()  # deep copy
d3[2][1] = 100
print(d3) 
print(d2)

[[  1   2]
 [  3   4]
 [  5 100]
 [  7   8]
 [  9  10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### Concatenate two arrays [1,2,3] and [4,5,6].

In [57]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


#### Stack two 3×3 identity matrices vertically.

In [62]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
arr3 = np.vstack((arr1,arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


#### Split an array of size 20 into 4 equal chunks.


In [64]:
arr1 = np.random.randint(1,20,20)
print(arr1)

[18  8  4 14  8  6 17 12 10  8 12  6 19  1  7 16 18  9 10  8]


In [67]:
print(np.split(arr1,2))

[array([18,  8,  4, 14,  8,  6, 17, 12, 10,  8], dtype=int32), array([12,  6, 19,  1,  7, 16, 18,  9, 10,  8], dtype=int32)]


#### Show with code how modifying a .view() changes the original array but .copy() does not

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = a1.view()
a2[3] = 100
print(a2)
print(a1)   # affects both original and duplicate array

[  1   2   3 100   5]
[  1   2   3 100   5]


In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = a1.copy()
a2[3] = 100
print(a2)
print(a1)   # only affects copy

[  1   2   3 100   5]
[1 2 3 4 5]


#### Create two arrays of shape (2×3) and horizontally stack them into a (2×6) array.

In [74]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
stacked = np.hstack((a,b))
print(stacked)
print(stacked.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [75]:
import numpy as np
x = np.arange(16.0).reshape(4, 4)
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [76]:

np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]