# Random array generation, statistical and math functions. Functions: random.rand(), random.randint(), mean(), sum().

In [1]:
import numpy as np

#### random.rand(), random.randint()

In [4]:
a = np.random.rand(3,5)
print(a)

[[0.30040334 0.17461763 0.97260562 0.41918625 0.37629914]
 [0.82916477 0.5836255  0.81962989 0.29959809 0.86933333]
 [0.72937532 0.78266238 0.95276784 0.65311239 0.51597698]]


to get random float values between 1 and 20

In [5]:
nums = 1 + (20-1)*np.random.rand(10)
print(nums)

[17.01889689  7.86969296 11.95946733 17.12251906  5.5211552  12.38536466
  1.91487478 15.66376473 14.85018617  1.90791652]


In [6]:
a1 = np.random.randint(1,31,(6,5))
print(a1)

[[14 21 15 28  2]
 [21  7  4  3 24]
 [12 11 20 12 18]
 [12 11  2  7 10]
 [ 6 26  7 22  7]
 [12 29  4 29 10]]


In [7]:
# Draw 10 samples from a power distribution with exponent 5
samples = np.random.power(5, 10)
print(samples)

[0.81178594 0.50945836 0.99586733 0.53968978 0.86568014 0.76174368
 0.84330496 0.7820057  0.86592818 0.97718881]


#### mean(), sum()

In [9]:
a3 = np.array([1,2,3,4])
print(np.sum(a3))

10


In [10]:
print(np.mean(a3))

2.5


In [11]:
print(np.prod(a3))

24


In [12]:
print(np.cumsum(a3))

[ 1  3  6 10]


In [13]:
print(np.cumprod(a3))

[ 1  2  6 24]


#### Generate random integers (1–100).

In [14]:
rand100 = np.random.randint(1,101,(10,10))
print(rand100)

[[ 79  67  21  97  67  64  77  85  92  67]
 [ 14  85  79  57  73   9   9  26  34  42]
 [ 67  87  71  95  56   2  32  45  21  72]
 [ 16  25  24  83  16  28  69  32  73  24]
 [ 12  13  17  40  46  96  78  21  18  95]
 [  4  49  86  58  10  57  20  66  48  73]
 [ 97  12  52  14  92  70   5  46  47  50]
 [ 25   7  12   8  36  32  29  69  24  23]
 [ 62  51  60  60   1  42  71  54  68  24]
 [ 34  86  15  33  18  11  75  75 100  61]]


#### Compute sum, mean, standard deviation.

In [15]:
print(np.sum(rand100))

4740


In [16]:
print(np.mean(rand100))

47.4


In [17]:
print(np.std(rand100))

28.347133893923033


#### Create an identity matrix with eye().

In [21]:
ident = np.eye(4,4, dtype=int)
print(ident)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### Generate 5 random integers between 1 and 20.

In [22]:
randinteger = np.random.randint(1,21,5)
print(randinteger)

[ 6 11  2  6  8]


#### Create a 5×5 random integer matrix and find its mean and standard deviation.

In [24]:
rand5x5 = np.random.randint(1,100,(5,5))
print(rand5x5)

[[14 73 58 33 76]
 [74 96 49 42 55]
 [94 43 36 34  7]
 [51 87 52 82 98]
 [54 52 18 45 67]]


In [25]:
print(np.mean(rand5x5))

55.6


In [26]:
print(np.std(rand5x5))

24.656033744298778


#### Find the most frequent number in a random array of 100 integers (0–10).


In [28]:
arr1 = np.random.randint(1,11,100)
print(arr1)

[ 9 10  9  6  9  3  4  5  7  9  6  5  6  3  4  3  7 10  4  8  2  6  3 10
  5  3  2  7  7  8  5  8  9  6 10  7  1  9  9  6  3 10  2 10  7  6  5  7
  2  8  7 10  7  4  5  7  4  8  7  1  8  1  9  6  4  4  2  1 10  8  4  6
  8  8  1  7  3 10 10 10  4 10  9  3  3  4  4  8  8  9  4  7  8  8  5  8
  6  7  1  1]


In [29]:
values, count = np.unique(arr1, return_counts=True)
print(values)
print(count)

[ 1  2  3  4  5  6  7  8  9 10]
[ 7  5  9 12  7 10 14 14 10 12]


In [32]:
max_count = count.max()
print(max_count)

14


In [35]:
most_freq = values[count == max_count]
print("Most frequent:", most_freq, "appearing", max_count, "times")

Most frequent: [7 8] appearing 14 times


#### Normalize a 4×4 random integer array (scale values between 0 and 1).


In [40]:
arr = np.random.randint(1,30,(4,4))
print(arr)

[[ 4  1 19 10]
 [ 6 14 24  6]
 [15  3  1 11]
 [26  9  6 11]]


min-max normalization

In [41]:
min_val = arr.min()
max_val = arr.max()

In [42]:
normarr = (arr - min_val) / (max_val - min_val)
print(normarr)

[[0.12 0.   0.72 0.36]
 [0.2  0.52 0.92 0.2 ]
 [0.56 0.08 0.   0.4 ]
 [1.   0.32 0.2  0.4 ]]


#### Create two random 3×3 matrices and perform matrix multiplication."

In [45]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print()
print(b)

[[1 8 4]
 [6 6 9]
 [1 5 6]]

[[3 3 6]
 [6 2 8]
 [4 9 1]]


In [46]:
multiarr = np.multiply(a,b)
print(multiarr)

[[ 3 24 24]
 [36 12 72]
 [ 4 45  6]]
