In [1]:
import numpy as np

 Create a 1D NumPy array with 15 evenly spaced numbers between 5 and 25.


In [31]:
arr = np.linspace(5,26,15, dtype=int)
print(arr)

[ 5  6  8  9 11 12 14 15 17 18 20 21 23 24 26]


Generate a 4x4 matrix filled with random integers between 50 and 100.


In [3]:
arr2 = np.random.randint(50,100,(4,4))
print(arr2)

[[53 97 66 61]
 [60 96 69 73]
 [96 68 76 90]
 [96 53 51 65]]


Create a NumPy array of ones with a shape of (3, 4).


In [6]:
arr3 = np.ones((4,4), dtype=int)
print(arr3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Create a 1D array of 10 random numbers and multiply each element by 2.


In [7]:
arr4 = np.random.randint(1,20,10)
print(arr4)
print(arr4*2)

[18  7  6 19  3 11  9 12 19  5]
[36 14 12 38  6 22 18 24 38 10]


 Generate a 2D array of shape (6, 3) filled with random floating-point numbers between 0 and 1.


In [9]:
sixbythree = np.random.rand(6,3)
print(sixbythree)

[[0.51024996 0.17192135 0.60431731]
 [0.94389886 0.94732376 0.03094633]
 [0.93013675 0.55493333 0.57769755]
 [0.62403973 0.86377685 0.13583788]
 [0.24286692 0.16094467 0.32858044]
 [0.36738216 0.28303576 0.75040875]]


Given the array arr = np.arange(1, 21).reshape(5, 4)
   - The first column
 
   - The third row
   
   - A sub-matrix consisting of rows 2 and 3, and columns 1 to 2

In [10]:
arr = np.arange(1, 21).reshape(5, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [13]:
print("first col:\n",arr[:, :1])

first col:
 [[ 1]
 [ 5]
 [ 9]
 [13]
 [17]]


In [16]:
print("3rd row:\n",arr[2:3, :])

3rd row:
 [[ 9 10 11 12]]


In [20]:
print(arr[1:3, 0:2])

[[ 5  6]
 [ 9 10]]


Create an array arr = np.arange(10, 31).reshape(7, 3)
   - The element at position (2, 1)
   
   - The last 3 elements of the second column:
    
   - The elements in the first and third columns of the last two rows

In [36]:
arr = np.arange(10, 31).reshape(7, 3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [37]:
print(arr[2][1])

17


In [40]:
print(arr[-3:, 1])

[23 26 29]


Slice a 1D array to retrieve every third element starting from index 0.


In [46]:
arr = np.arange(1,10)
print(arr)
print(arr[2::3])

[1 2 3 4 5 6 7 8 9]
[3 6 9]


Create a 1D NumPy array of integers from 1 to 20 

   - Calculate the square of each element
  
   - Subtract 5 from each element

In [ ]:
arr1 = np.arange(1,21)
sqaure = np.square(arr1)
print(sqaure)


[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [53]:
print(arr1 - 5)

[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Given an array arr = np.array([2, 3, 4, 5])

- The exponential of each element
     
- The logarithm base 2 of each element

In [54]:
arr = np.array([2, 3, 4, 5])
print(np.exp(arr))
print(np.log2(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.5849625  2.         2.32192809]
